name:         sapnwrfc
abstract:     SAP NW RFC for Perl
author:
  - Piers Harding <piers@cpan.org>
  - Gerhard Lausser <gerhard.lausser@consol.de>
license:      Perl
version:      0.50
resources:
  license: http://dev.perl.org/licenses/
  homepage: https://github.com/lausser/perl-sapnwrfc
  repository: https://github.com/lausser/perl-sapnwrfc
  bugtracker: https://github.com/lausser/perl-sapnwrfc/issues
version_from: sapnwrfc.pm
installdirs:  site
requires:
   perl: 5.008
   YAML: 0
   Test::More: 0
distribution_type: module
generated_by: ME
